In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder # para realizar el Label Encoding 
from sklearn.preprocessing import OneHotEncoder  # para realizar el One-Hot Encoding
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams["figure.figsize"] = (10,8)
import warnings
warnings.filterwarnings('ignore')

In [22]:
df = pd.read_csv("../ficheros/diamons_estandarizados.csv", index_col= 0)
df.head(2)

,carat,cut,color,clarity,depth,table,price,x,y,z
0,-0.746032,Ideal,E,SI2,-0.214286,-0.666667,326,-0.931818,-0.91954,-0.909091
1,-0.777778,Premium,E,SI1,-1.428571,1.333333,326,-0.965909,-1.00000,-1.018182

### INFORMACIÓN SOBRE NUESTRAS VARIABLES
---

- **carat** is a measure of diamond weight. One carat is equivalent to 0.2 grams.

- **clarity** refers to how clear a diamond is. Diamonds often contain imperfections like cracks or mineral deposits. The fewer and less noticeable a diamond’s imperfections, the better its clarity. clarity contains 8 ordered levels, from “I1” (the worst) to “IF” (the best).

- **color** refers to the color of the diamond. Colorless diamonds are considered better than diamonds with a yellow tint. Diamonds contains diamonds of 7 different colors, represented by different letters. “D” - “F” diamonds are considered colorless, while “G” - “J” diamonds have a very faint color. This grading is determined by the intensity of the color, and from least to most saturated are graded as faint, very light, light, fancy light, fancy, fancy intense, fancy vivid, fancy dark, or fancy deep. The deeper and more intense the color, the more expensive the diamond will be.

    *Helpful Hint:* Diamond prices decline or increase in alphabetical order. For example, a diamond with a G colour grade is less expensive than a diamond with a D colour grade.

- **cut** refers to how a rough diamond is shaped into a finished diamond. Better cuts create more symmetrical and luminous diamonds. cut has 5 ordered levels: “Fair,” “Good,” “Very Good,” “Premium,” “Ideal.”

- **x**, **y**, **z**, **depth**, and **table** are various measures of a diamond’s size, in millimeters

Vamos a escoger el método map para realizar el encoding porque queremos seleccionar nosotras el orden de las etiquetas según nuestra investigación

In [23]:
df.cut.unique() # El orden según la información que encontramos es de más caro a más barato: "Ideal", "Premium", "Very good", "Good", "Fair"

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [24]:
# Vamos a hacer el encoding de cut con el método map
dict_cut = {"Fair": 0, "Good": 1, "Very Good": 2, "Premium": 3, "Ideal": 4}

In [25]:
df["cut_map"] = df["cut"].map(dict_cut)

In [26]:
df.sample(6)

,carat,cut,color,clarity,depth,table,price,x,y,z,cut_map
36020,-0.285714,Premium,E,SI2,-0.500000,0.000000,1088,-0.204545,-0.264368,-0.245455,3
25100,-0.619048,Very Good,E,VS2,0.000000,0.666667,680,-0.732955,-0.695402,-0.681818,2
20787,0.888889,Very Good,F,VS2,-0.285714,0.666667,9071,0.721591,0.793103,0.736364,2
44087,0.000000,Very Good,J,VS2,-2.571429,1.000000,1896,0.153409,0.183908,-0.009091,2
4516,0.333333,Premium,E,SI2,-0.500000,0.666667,3639,0.369318,0.356322,0.336364,3
36686,-0.428571,Ideal,D,VS2,0.000000,-0.333333,1129,-0.431818,-0.442529,-0.409091,4

In [27]:
# Vamos a hacer lo mismo para la variable color
df.color.unique() # El orden sería de más barato a más barato:J, I, H, G, F, E, D

array(['E', 'I', 'J', 'H', 'F', 'G', 'D'], dtype=object)

In [28]:
# Vamos a hacer el encoding de color con el método map
dict_color = {"J": 0, "I": 1, "H": 2, "G": 3, "F": 4, "E": 5, "D": 6}

In [29]:
df["color_map"] = df["color"].map(dict_color)

In [30]:
df.sample(6)

,carat,cut,color,clarity,depth,table,price,x,y,z,cut_map,color_map
36117,-0.492063,Premium,G,VVS1,-1.000000,0.666667,1095,-0.494318,-0.477011,-0.518182,3,3
30211,-0.634921,Premium,E,VS2,0.214286,0.333333,844,-0.727273,-0.741379,-0.690909,3,5
5166,0.317460,Premium,G,SI1,-0.357143,1.000000,3774,0.329545,0.321839,0.309091,3,3
15306,0.476190,Good,D,VS2,2.785714,-0.666667,6163,0.329545,0.367816,0.581818,1,6
12516,0.492063,Ideal,G,SI1,-0.142857,0.000000,5273,0.460227,0.425287,0.445455,4,3
28226,-0.634921,Premium,H,VVS2,-0.714286,0.333333,776,-0.693182,-0.712644,-0.709091,3,2

In [31]:
df.clarity.unique() # Según la información recopilada, el orden de importe según clarity es (de menor a mayor): I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF

array(['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF'],
      dtype=object)

In [32]:
dict_clarity = {"I1": 0, "SI2": 1, "SI1": 2, "VS2": 3, "VS1": 4, "VVS2": 5, "VVS1": 6, "IF":7}

In [33]:
df["clarity_map"] = df["clarity"].map(dict_clarity)

In [34]:
df.sample(6)

,carat,cut,color,clarity,depth,table,price,x,y,z,cut_map,color_map,clarity_map
20440,0.825397,Ideal,G,VS1,0.571429,-0.866667,8830,0.670455,0.718391,0.754545,4,3,4
47827,0.031746,Very Good,I,VVS2,0.642857,-1.000000,2386,0.085227,0.126437,0.172727,2,1,5
35408,-0.174603,Fair,H,SI2,1.928571,0.000000,1059,-0.125000,-0.241379,-0.009091,0,2,1
10595,0.476190,Very Good,H,SI1,0.714286,-0.333333,4830,0.420455,0.454023,0.509091,2,2,2
39088,-0.301587,Ideal,F,SI1,0.071429,-0.333333,1346,-0.272727,-0.241379,-0.227273,4,4,2
6602,0.539683,Very Good,G,SI2,-1.071429,1.666667,4084,0.517045,0.563218,0.463636,2,3,1

In [35]:
df.drop(columns=["cut", "color", "clarity"], axis=1, inplace= True)

In [36]:
df.to_csv("../ficheros/diamons_estand_enconding.csv")

Hacemos lo mismo para el csv sin estandarizar

In [37]:
df2= pd.read_csv("../ficheros/diamons_01.csv", index_col = 0)
df2.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [38]:
df2["cut_map"] = df2["cut"].map(dict_cut)
df2["color_map"] = df2["color"].map(dict_color)
df2["clarity_map"] = df2["clarity"].map(dict_clarity)

In [39]:
df2.sample(6)

,carat,cut,color,clarity,depth,table,price,x,y,z,cut_map,color_map,clarity_map
20101,1.22,Very Good,F,VS2,62.3,57.0,8575,6.80,6.84,4.25,2,4,3
48274,0.53,Ideal,D,VS2,61.7,55.0,1956,5.23,5.21,3.22,4,6,3
38982,0.39,Premium,F,VS2,58.8,59.0,1053,4.83,4.80,2.83,3,4,3
21000,1.21,Ideal,E,VS2,62.4,54.0,9215,6.86,6.80,4.26,4,5,3
49016,0.50,Premium,F,VVS2,61.9,58.0,2052,5.07,5.10,3.15,3,4,5
28868,0.32,Premium,F,SI1,62.3,55.0,684,4.44,4.39,2.75,3,4,2

In [40]:
df2.drop(columns=["cut", "color", "clarity"], axis=1, inplace= True)

In [41]:
df2.to_csv("../ficheros/diamons_enconding.csv")